spring.application.name=backend

# spring.datasource.url=jdbc:postgresql://localhost:5432/lostcampus_db
# spring.datasource.username=postgres
# spring.datasource.password=admin

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lostcampus_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:diska4x9b}
cloudinary.api-key=${CLOUDINARY_API_KEY:493323274182787}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:K453jOvJ0mudQ9syChfBmNtFR3o}

# Multipart / File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Ejecutar automaticamente schema.sql al iniciar la aplicacion
spring.sql.init.mode=never

# JPA
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080

# Jackson Naming Strategy
spring.jackson.property-naming-strategy=SNAKE_CASE

# Mail (Gmail SMTP SSL)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${SPRING_MAIL_USERNAME:tetsuya12326@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:yoni rzqd eetf ning}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false

# CORS Configuration
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}
